### PR TITLE
fix: Do not npmignore built asset

### PR DESCRIPTION
**Pull request by SpainTrain**
This fixes a bug from #2

- Added a blank `.npmignore` so the `lib` dir exists in published
  package

---
This change is [Reviewable](https://reviewable.io/reviews/exelban/react-swipe-component/3)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Sorry about this.  npm uses `.gitignore` by default to ignore files in the published module.  To ensure that `./lib` shows up in the published module, we want a blank `.npmignore` file (`node_modules` is ignored by npm by default)

**Comment by exelban** [comment]
@SpainTrain Ok. Wait please for a few minutes, i make changes.

**Comment by SpainTrain** [comment]
Sure.

you can use `npm pack` to see this work https://docs.npmjs.com/cli/pack

**Comment by exelban** [comment]
@SpainTrain Please, check changes. If all right, i will publish new version.

**Comment by SpainTrain** [comment]
made an FYI note on one of the commits, lgtm otherwise :shipit:

**Comment by exelban** [comment]
@SpainTrain Add `"prepublish": "npm run build"`. Now all right?

**Comment by exelban** [comment]
@SpainTrain ok i publish new version to npm. Please check it.

**Comment by SpainTrain** [comment]
yup, greenkeeper opened a PR to update, CI is running.  We will see soon :-)

**Comment by exelban** [comment]
@SpainTrain CI passed.

**Comment by SpainTrain** [comment]
all passed, thanks!!

:tada: :clinking_glasses: :balloon: :beers:

**Comment by exelban** [comment]
@SpainTrain thanks for your help and contribution.

**Pull request closed without merging**
